#!/usr/bin/env python3
"""Regenerate Resources/en.lproj/Localizable.strings from the source.

Stands in for Apple's `genstrings`, which ships with Xcode and is not present
on a Command Line Tools install (the same reason `swift test` cannot run here).

Scans for NSLocalizedString("key", comment: "note") and writes every key it
finds, keeping the English value equal to the key so an untranslated build
reads exactly as it does today.

    tools/l10n-extract.py           # rewrite the table
    tools/l10n-extract.py --check   # exit 1 if the table is out of date (CI)
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = os.path.join(ROOT, "Sources", "ClaudeNotch")
TABLE = os.path.join(ROOT, "Resources", "en.lproj", "Localizable.strings")

# NSLocalizedString("key", comment: "note"). Keys are literals with no
# interpolation: a \( inside one would mean the string is built at runtime and
# cannot be a key, so those are reported rather than silently half-extracted.
CALL = re.compile(
    r'NSLocalizedString\(\s*"((?:[^"\\]|\\.)*)"\s*,\s*comment:\s*"((?:[^"\\]|\\.)*)"\s*\)'
)
INTERPOLATED = re.compile(r'NSLocalizedString\(\s*"[^"]*\\\(')


def scan():
    found = {}
    bad = []
    for name in sorted(os.listdir(SOURCES)):
        if not name.endswith(".swift"):
            continue
        path = os.path.join(SOURCES, name)
        text = open(path, encoding="utf-8").read()
        for m in INTERPOLATED.finditer(text):
            line = text[:m.start()].count("\n") + 1
            bad.append(f"{name}:{line}")
        for m in CALL.finditer(text):
            key, comment = m.group(1), m.group(2)
            found.setdefault(key, comment)
    return found, bad


def render(found):
    out = [
        "/* ClaudeNotch, English (source language).",
        "   Generated by tools/l10n-extract.py. Do not edit by hand: add or",
        "   change NSLocalizedString in Sources and run the script again.",
        "   A translation is a sibling <lang>.lproj/Localizable.strings. */",
        "",
    ]
    for key in sorted(found):
        comment = found[key]
        if comment:
            out.append(f"/* {comment} */")
        out.append(f'"{key}" = "{key}";')
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main():
    found, bad = scan()
    if bad:
        print("NSLocalizedString keys cannot contain interpolation:", file=sys.stderr)
        for b in bad:
            print("  " + b, file=sys.stderr)
        return 1
    text = render(found)
    check = "--check" in sys.argv
    current = open(TABLE, encoding="utf-8").read() if os.path.exists(TABLE) else None
    if check:
        if current != text:
            print("Resources/en.lproj/Localizable.strings is out of date. "
                  "Run tools/l10n-extract.py.", file=sys.stderr)
            return 1
        print(f"{len(found)} keys, table up to date.")
        return 0
    os.makedirs(os.path.dirname(TABLE), exist_ok=True)
    open(TABLE, "w", encoding="utf-8").write(text)
    print(f"wrote {os.path.relpath(TABLE, ROOT)} ({len(found)} keys)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
